# Generated by Django 2.2.4 on 2019-09-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name used by other apps to reference this metadata type. Do not use python reserved words, or spaces.', max_length=48, unique=True, verbose_name='Name')),
                ('label', models.CharField(max_length=48, verbose_name='Label')),
                ('default', models.CharField(blank=True, help_text="Enter a template to render. Use Django's default templating language (https://docs.djangoproject.com/en/1.11/ref/templates/builtins/)", max_length=128, null=True, verbose_name='Default')),
                ('lookup', models.TextField(blank=True, help_text="Enter a template to render. Must result in a comma delimited string. Use Django's default templating language (https://docs.djangoproject.com/en/1.11/ref/templates/builtins/).", null=True, verbose_name='Lookup')),
            ],
            options={
                'verbose_name': 'Metadata type',
                'verbose_name_plural': 'Metadata types',
                'ordering': ('label',),
            },
        ),
    ]
