# Generated by Django 2.2.4 on 2019-09-03 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=20, verbose_name='Value')),
                ('metadata_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.MetadataType')),
            ],
        ),
    ]
