# Generated by Django 2.2.4 on 2019-09-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_metadatavalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_value', models.ManyToManyField(to='metadata.MetadataValue')),
            ],
        ),
    ]
