# Generated by Django 2.2.4 on 2019-09-05 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='metadata_value',
        ),
        migrations.AddField(
            model_name='case',
            name='name',
            field=models.CharField(default='testcase', help_text='Name used by other apps to reference this metadata type. Do not use python reserved words, or spaces.', max_length=48, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadatavalue',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='metadata.Case'),
            preserve_default=False,
        ),
    ]
