# Generated by Django 2.2.4 on 2019-09-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_auto_20190905_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='name',
            field=models.CharField(default='dte', max_length=48, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
