version: '3'

services:

  djangoapp:
    build: ./backend
    restart: 'always'
    volumes:
      - ./backend:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/media  # <-- bind the media volume

    networks:
      - nginx_network
      - database_network
    depends_on:
      - database
    expose:
      - "8000"



  frontend:
    build: ./frontend
    restart: 'always'
    volumes:
      - ./frontend:/app
  
      
    networks:
      - nginx_network

    expose:
      - "8080"

  nginx:
    image: nginx:1.13
    restart: 'always'
    ports:
      - 8003:80
    volumes:
      - ./backend/config/nginx/conf.d-development:/etc/nginx/conf.d
  
      - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/media  # <-- bind the media volume

    depends_on:
      - djangoapp
    networks:
      - nginx_network

  database:
    image: postgres:12.1
    restart: 'always'
    env_file:
      - ./backend/config/db/.env
    networks:
      - database_network
    volumes:
      - database_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  database_volume:
  frontend_volume:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume