# Generated by Django 3.0 on 2020-01-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0003_loadfixtures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileversion',
            name='original_filename',
            field=models.CharField(max_length=255, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
