# Generated by Django 2.2.4 on 2019-11-21 17:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import documentmanager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentmanager.Item')),
            ],
            bases=('documentmanager.item',),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentmanager.Item')),
                ('folder_name', models.CharField(max_length=200, verbose_name='folder name')),
            ],
            bases=('documentmanager.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_parent', to='documentmanager.Folder'),
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileuploaded', models.FileField(unique=True, upload_to=documentmanager.models.generate_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('original_filename', models.CharField(max_length=200, verbose_name='Filename')),
                ('uploadtime', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_file', to='documentmanager.File')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='current_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_version', to='documentmanager.FileVersion'),
        ),
    ]
