# Generated by Django 2.2.4 on 2019-11-21 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0003_item_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='modification_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Modified'),
            preserve_default=False,
        ),
    ]
