# Generated by Django 2.2.4 on 2019-11-21 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0004_item_modification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='modification_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified'),
        ),
    ]
