# Generated by Django 2.2.4 on 2019-11-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0006_auto_20191122_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.TextField(max_length=1450),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_r', to='documentmanager.Item'),
        ),
    ]
