# Generated by Django 2.2.4 on 2019-11-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0010_auto_20191125_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_fk',
            new_name='user',
        ),
    ]
