# Generated by Django 2.2.4 on 2019-11-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0011_auto_20191126_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_version', to='documentmanager.FileVersion'),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_file', to='documentmanager.File'),
        ),
    ]
