# Generated by Django 2.2.4 on 2019-12-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0013_auto_20191203_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='icon',
            field=models.FilePathField(blank=True, editable=False, null=True),
        ),
    ]
