# Generated by Django 2.2.4 on 2019-12-04 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentmanager', '0014_item_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='creator',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='FileVersion_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
