# Generated by Django 2.2.4 on 2019-10-01 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Χρεώσεις_Χειριστών',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ημερομηνία_χρέωσης', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Χρέωσης')),
                ('ημερομηνία_ολοκλήρωσης', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Ολοκλήρωσης')),
                ('τύπος_χρέωσης', models.CharField(choices=[('ΑΙΤΗΜΑ', 'Αίτημα'), ('ΠΡΩΤΟΔΙΚΕΙΑ', 'Διοικητικά Πρωτοδικεία'), ('ΛΟΙΠΗ_ΑΛΛΗΛΟΓΡΑΦΙΑ', 'Λοιπή Αλληλογραφία')], max_length=255)),
                ('document_pk', models.IntegerField(blank=True, help_text='Αφορά τον αριθμό καταχώρησης στο ψηφιακό αρχείο μας.', null=True, verbose_name='ID εισερχόμενου εγγράφου')),
                ('σχόλια', models.CharField(blank=True, max_length=450, verbose_name='Σχόλια')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdby', to=settings.AUTH_USER_MODEL)),
                ('χειριστής', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Χρεώσεις_Χειριστών',
            },
        ),
        migrations.CreateModel(
            name='Documents_pk',
            fields=[
                ('document_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='documents', serialize=False, to='documentmanager.Χρεώσεις_Χειριστών')),
                ('apanthsh_pk', models.IntegerField(blank=True, help_text='Αφορά τον αριθμό καταχώρησης στο ψηφιακό αρχείο μας.', null=True, verbose_name='ID απάντησης στο ψηφιακό μας αρχείο')),
            ],
        ),
        migrations.CreateModel(
            name='Διοικητικά_Πρωτοδικεία',
            fields=[
                ('χρεώσεις', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='πρωτοδικείο', serialize=False, to='documentmanager.Χρεώσεις_Χειριστών')),
                ('πρωτοδικείο', models.CharField(blank=True, max_length=50, verbose_name='Διοικητικό Πρωτοδικείο')),
                ('αριθμός_πρωτοκόλλου', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Πρωτοκόλλου')),
                ('εσωτερικό_πρωτ', models.CharField(blank=True, max_length=50, verbose_name='Εσωτερικό Πρωτόκολλο')),
                ('επώνυμο', models.CharField(blank=True, max_length=50, verbose_name='Επώνυμο')),
                ('όνομα', models.CharField(blank=True, max_length=50, verbose_name='Όνομα')),
                ('ημερομηνία_γέννησης', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Γέννησης')),
                ('δκα', models.CharField(blank=True, max_length=50, verbose_name='ΔΚΑ')),
                ('ενέργειες', models.TextField(blank=True, max_length=200, verbose_name='Ενέργειες')),
                ('πρωτόκολλο_απάντησης', models.CharField(blank=True, max_length=20, verbose_name='Πρωτόκολλο απάντησης')),
            ],
        ),
        migrations.CreateModel(
            name='Λοιπή_Αλληλογραφία',
            fields=[
                ('χρεώσεις', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='λοιπη_αλληλογραφία', serialize=False, to='documentmanager.Χρεώσεις_Χειριστών')),
                ('αποστολέας', models.CharField(blank=True, max_length=50, verbose_name='Αποστολέας')),
                ('αριθμός_πρωτοκόλλου', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Πρωτοκόλλου')),
                ('ημερομηνία_εγγράφου', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Εγγράφου')),
                ('αριθμός_πρωτοκόλλου_εισερχόμενης_αλληλογραφίας', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Πρωτοκόλλου Εισερχόμενης Αλληλογραφίας')),
                ('ημερομηνία_πρωτοκόλλου_εισερχόμενης_αλληλογραφίας', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Πρωτοκόλλου Εισερχόμενης Αλληλογραφίας')),
                ('πρωτόκολλο_απάντησης', models.CharField(blank=True, max_length=20, verbose_name='Πρωτόκολλο απάντησης')),
                ('ενέργειες', models.TextField(blank=True, max_length=200, verbose_name='Ενέργειες')),
                ('εμπλεκόμενα_άτομα', models.TextField(blank=True, max_length=200, verbose_name='Εμπλεκόμενα άτομα')),
            ],
        ),
        migrations.CreateModel(
            name='Χρεώσεις_αιτήματα',
            fields=[
                ('χρεώσεις', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='αίτημα', serialize=False, to='documentmanager.Χρεώσεις_Χειριστών')),
                ('επώνυμο', models.CharField(blank=True, max_length=20, verbose_name='Επώνυμο')),
                ('όνομα', models.CharField(blank=True, max_length=20, verbose_name='Όνομα')),
                ('ημερομηνία_γέννησης', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Γέννησης')),
                ('αριθμός_πρωτοκόλλου', models.CharField(blank=True, max_length=20, verbose_name='Αριθμός Πρωτοκόλλου')),
                ('ημερομηνία_πρωτοκόλλου', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Πρωτοκόλλου')),
                ('δκα', models.CharField(blank=True, max_length=20, verbose_name='ΔΚΑ')),
                ('απάντηση_που_δώσαμε', models.CharField(blank=True, max_length=60, verbose_name='Απάντηση που δώσαμε')),
                ('πρωτόκολλο_απάντησης', models.CharField(blank=True, max_length=20, verbose_name='Πρωτόκολλο απάντησης')),
                ('στοιχεία_παραλήπτη', models.CharField(blank=True, max_length=50, verbose_name='Στοιχεία Παραλήπτη')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Email Αποστολή Αποφάσεων')),
            ],
            options={
                'verbose_name_plural': 'Αιτήματα',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία')),
                ('comment', models.TextField(max_length=450, verbose_name='Σχόλιο')),
                ('χειριστής', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('χρεώσεις', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documentmanager.Χρεώσεις_Χειριστών')),
            ],
        ),
    ]
