# Generated by Django 2.2.4 on 2019-10-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=40, verbose_name='Βαθμός')),
                ('rank_short', models.CharField(max_length=40, verbose_name='Συντομογραφία')),
                ('rank_order', models.IntegerField(verbose_name='Βαθμίδα')),
            ],
        ),
    ]
