# Generated by Django 2.2.4 on 2019-09-18 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Λοιπή_Αλληλογραφία',
            fields=[
                ('χρεώσεις', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='λοιπη_αλληλογραφία', serialize=False, to='main.Χρεώσεις_Χειριστών')),
                ('αποστολέας', models.CharField(blank=True, max_length=50, verbose_name='Αποστολέας')),
                ('αριθμός_πρωτοκόλλου', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Πρωτοκόλλου')),
                ('ημερομηνία_εγγράφου', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Εγγράφου')),
                ('αριθμός_πρωτοκόλλου_εισερχόμενης_αλληλογραφίας', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Πρωτοκόλλου Εισερχόμενης Αλληλογραφίας')),
                ('ημερομηνία_πρωτοκόλλου_εισερχόμενης_αλληλογραφίας', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Πρωτοκόλλου Εισερχόμενης Αλληλογραφίας')),
                ('πρωτόκολλο_απάντησης', models.CharField(blank=True, max_length=20, verbose_name='Πρωτόκολλο απάντησης')),
                ('ενέργειες', models.TextField(blank=True, max_length=200, verbose_name='Ενέργειες')),
                ('εμπλεκόμενα_άτομα', models.TextField(blank=True, max_length=200, verbose_name='Εμπλεκόμενα άτομα')),
            ],
        ),
        migrations.AddField(
            model_name='διοικητικά_πρωτοδικεία',
            name='δκα',
            field=models.CharField(blank=True, max_length=50, verbose_name='ΔΚΑ'),
        ),
        migrations.AddField(
            model_name='διοικητικά_πρωτοδικεία',
            name='πρωτόκολλο_απάντησης',
            field=models.CharField(blank=True, max_length=20, verbose_name='Πρωτόκολλο απάντησης'),
        ),
        migrations.AlterField(
            model_name='διοικητικά_πρωτοδικεία',
            name='αριθμός_πρωτοκόλλου',
            field=models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Πρωτοκόλλου'),
        ),
        migrations.AlterField(
            model_name='διοικητικά_πρωτοδικεία',
            name='επώνυμο',
            field=models.CharField(blank=True, max_length=50, verbose_name='Επώνυμο'),
        ),
        migrations.AlterField(
            model_name='διοικητικά_πρωτοδικεία',
            name='εσωτερικό_πρωτ',
            field=models.CharField(blank=True, max_length=50, verbose_name='Εσωτερικό Πρωτόκολλο'),
        ),
        migrations.AlterField(
            model_name='διοικητικά_πρωτοδικεία',
            name='πρωτοδικείο',
            field=models.CharField(blank=True, max_length=50, verbose_name='Διοικητικό Πρωτοδικείο'),
        ),
        migrations.AlterField(
            model_name='διοικητικά_πρωτοδικεία',
            name='όνομα',
            field=models.CharField(blank=True, max_length=50, verbose_name='Όνομα'),
        ),
        migrations.AlterField(
            model_name='χρεώσεις_αιτήματα',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='Email Αποστολή Αποφάσεων'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία')),
                ('comment', models.CharField(blank=True, max_length=450, verbose_name='Σχόλιο')),
                ('χειριστής', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('χρεώσεις', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.Χρεώσεις_Χειριστών')),
            ],
        ),
    ]
