# Generated by Django 2.2.4 on 2019-09-18 12:34

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190918_1200'),
    ]

    operations = [
        UnaccentExtension()
    ]
