# Generated by Django 2.2.4 on 2019-09-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190918_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='χρεώσεις_χειριστών',
            name='τύπος_χρέωσης',
            field=models.CharField(choices=[('ΑΙΤΗΜΑ', 'Αίτημα'), ('ΠΡΩΤΟΔΙΚΕΙΑ', 'Διοικητικά Πρωτοδικεία'), ('ΛΟΙΠΗ_ΑΛΛΗΛΟΓΡΑΦΙΑ', 'Λοιπή Αλληλογραφία')], max_length=255),
        ),
    ]
