# Generated by Django 2.2.4 on 2019-10-05 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='διοικητικά_πρωτοδικεία',
            name='ενέργειες',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Ενέργειες'),
        ),
        migrations.AlterField(
            model_name='διοικητικά_πρωτοδικεία',
            name='πρωτόκολλο_απάντησης',
            field=models.CharField(blank=True, max_length=50, verbose_name='Πρωτόκολλο απάντησης'),
        ),
    ]
