# Generated by Django 2.2.4 on 2019-10-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0004_auto_20191005_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=1450, verbose_name='Σχόλιο'),
        ),
    ]
