# Generated by Django 2.2.4 on 2019-09-18 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20190918_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='χρεώσεις_χειριστών',
            name='createdby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='createdby', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
