# Generated by Django 2.2.4 on 2019-09-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_χρεώσεις_χειριστών_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=450, verbose_name='Σχόλιο'),
        ),
    ]
