# Generated by Django 2.2.4 on 2019-10-08 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0005_auto_20191005_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Στρατολογικά',
            fields=[
                ('χρεώσεις', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='στρατολογικά', serialize=False, to='documentmanager.Χρεώσεις_Χειριστών')),
                ('αποστολέας', models.CharField(blank=True, max_length=50, verbose_name='Αποστολέας')),
                ('αριθμός_πρωτοκόλλου', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Πρωτοκόλλου')),
                ('αριθμός_πρωτοκόλλου_εισερχόμενης_αλληλογραφίας', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Πρωτοκόλλου Εισερχόμενης Αλληλογραφίας')),
                ('ημερομηνία_παράδοσης_στην_πληροφορική', models.CharField(blank=True, max_length=50, verbose_name='Ημερομηνία παράδοσης στην πληροφορική')),
                ('πρωτόκολλο_απάντησης', models.CharField(blank=True, max_length=20, verbose_name='Πρωτόκολλο απάντησης')),
            ],
        ),
        migrations.AlterField(
            model_name='λοιπή_αλληλογραφία',
            name='ενέργειες',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Ενέργειες'),
        ),
        migrations.AlterField(
            model_name='χρεώσεις_χειριστών',
            name='τύπος_χρέωσης',
            field=models.CharField(choices=[('ΑΙΤΗΜΑ', 'Αίτημα'), ('ΠΡΩΤΟΔΙΚΕΙΑ', 'Διοικητικά Πρωτοδικεία'), ('ΛΟΙΠΗ_ΑΛΛΗΛΟΓΡΑΦΙΑ', 'Λοιπή Αλληλογραφία'), ('ΣΤΡΑΤΟΛΟΓΙΚΑ', 'Στρατολογικά')], max_length=255),
        ),
    ]
