# Generated by Django 2.2.4 on 2019-10-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanager', '0006_auto_20191008_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='στρατολογικά',
            name='πρωτόκολλο_απάντησης',
        ),
    ]
